# Generated by Django 5.0.1 on 2024-01-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patients_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='slot',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
