# Generated by Django 5.0.1 on 2024-01-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patients_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.CharField(max_length=1)),
            ],
        ),
    ]
