# Generated by Django 5.0.1 on 2024-01-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patients_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='slot',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='slots',
            field=models.CharField(max_length=40),
        ),
    ]
